export const MenuItems=[
    {
        label:'Inicio',
        url:'#',
        cName:'nav-links'
    },
    {
        label:'Nosotros',
        url:'#',
        cName:'nav-links'
    },
    {
        label:'Productos',
        url:'#',
        cName:'nav-links'
    },
    {
        label:'Blog',
        url:'#',
        cName:'nav-links'
    },
    {
        label:'Contacto',
        url:'#',
        cName:'nav-links'
    },
]